name: iOS build

on: [push]

env:
  PROJECT_NAME: MyMobileGame
  GODOT_VERSION: 4.3
  GODOT_CHANNEL: stable
  GODOT_MONO: _mono # TODO : Boolean

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check is running on mac-os
        if: runner.os != 'macos'
        shell: bash
        run: exit 1

      - name: Cache Godot files
        id: cache-godot
        uses: actions/cache@v4
        with:
          path: |
            Godot.app
             /Users/runner/Library/Application\ Support/Godot/
          key: ${{ runner.os }}-godot-${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}${{ env.GODOT_MONO }}

      - name: Download and config Godot Engine linux server and templates
        shell: bash
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}${{ env.GODOT_MONO }}_macos.universal.zip
          wget -q https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}${{ env.GODOT_MONO }}_export_templates.tpz
          unzip Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}${{ env.GODOT_MONO }}_macos.universal.zip
          unzip Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}${{ env.GODOT_MONO }}_export_templates.tpz
          mkdir -p ~/Library/Application\ Support/Godot/export_templates/${{ env.GODOT_VERSION }}.${{ env.GODOT_CHANNEL }}.mono # TODO : Utiliser le bool. Attention, on a _mono et .mono
          mv templates/* ~/Library/Application\ Support/Godot/export_templates/${{ env.GODOT_VERSION }}.${{ env.GODOT_CHANNEL }}.mono  # TODO : Utiliser le bool. Attention, on a _mono et .mono
          #echo 'Export Templates'
          #ls ~/Library/Application\ Support/Godot/export_templates/
          #echo 'Export templates 4.3'
          #ls ~/Library/Application\ Support/Godot/export_templates/${{ env.GODOT_VERSION }}.${{ env.GODOT_CHANNEL }}.mono
          echo 'App support'
          ls ~/Library/Application\ Support
          

      - name: Godot iOS export
        shell: bash
        # run: ./Godot${{ env.GODOT_MONO }}.app/Contents/MacOS/Godot --headless --path ${{ inputs.working-directory }} --export-release iOS
        run: ./Godot${{ env.GODOT_MONO }}.app/Contents/MacOS/Godot --headless --path . --export-release iOS
        # run: echo 'Fake iOS Export for cache completion' 
